# Generated by OmopViewer 0.6.0
# Be careful editing this file

library(bslib)
library(dplyr)
library(DT)
library(gt)
library(markdown)
library(omopgenerics)
library(plotly)
library(purrr)
library(readr)
library(rlang)
library(shiny)
library(shinycssloaders)
library(shinyTree)
library(shinyWidgets)
library(sortable)
library(tidyr)
library(visOmopResults)
library(yaml)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "studyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "rawData", "preprocess.R"))
}

# uncomment to load the raw data
#rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "rawData"))
#rawData$group_level <- gsub("^[A-Za-z]*[0-9]+_", "", rawData$group_level)

# load shiny data
load(fileData)

# source functions
source(file.path(getwd(),"functions.R"))

