# Generated by OmopViewer 0.6.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_medication_adherence = FALSE,
    summarise_medication_adherence_cma_over_0.8 = FALSE,
    summarise_mean_continuous_adherence_window = FALSE,
    imas_hist = FALSE,
    #analysis1 = FALSE,
    #analysis2 = FALSE,
    #analysis3 = FALSE
  )
  
  # summarise_medication_adherence -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_medication_adherence <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_medication_adherence_cdm_name,
      input$summarise_medication_adherence_ingredient,
      input$summarise_medication_adherence_age_group,
      input$summarise_medication_adherence_sex,
      input$summarise_medication_adherence_variable_name,
      input$summarise_medication_adherence_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_medication_adherence, {
    if (updateButtons$summarise_medication_adherence == TRUE) {
      output$update_message_summarise_medication_adherence <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_medication_adherence <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_medication_adherence, {
    updateButtons$summarise_medication_adherence <- FALSE
  })
  
  ## get summarise_medication_adherence data
  getSummariseMedicationAdherenceData <- shiny::eventReactive(input$update_summarise_medication_adherence, {
    data[["summarise_medication_adherence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_medication_adherence_cdm_name,
        .data$variable_name %in% input$summarise_medication_adherence_variable_name,
        .data$estimate_name %in% input$summarise_medication_adherence_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$ingredient %in% input$summarise_medication_adherence_ingredient) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_medication_adherence_age_group,
        .data$sex %in% input$summarise_medication_adherence_sex
      ) |>
      dplyr::arrange(strata_level)
  })
  getSummariseMedicationAdherenceTidy <- shiny::reactive({
    tidyDT(getSummariseMedicationAdherenceData(), input$summarise_medication_adherence_tidy_columns, input$summarise_medication_adherence_tidy_pivot_estimates)
  })
  output$summarise_medication_adherence_tidy <- DT::renderDT({
    getSummariseMedicationAdherenceTidy()
  })
  output$summarise_medication_adherence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseMedicationAdherenceData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseMedicationAdherenceTable <- shiny::reactive({
    getSummariseMedicationAdherenceData() |>
      simpleTable(
        header = input$summarise_medication_adherence_table_header,
        group = input$summarise_medication_adherence_table_group_column,
        hide = input$summarise_medication_adherence_table_hide
      )
  })
  output$summarise_medication_adherence_table <- gt::render_gt({
    getSummariseMedicationAdherenceTable()
  })
  output$summarise_medication_adherence_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_medication_adherence_table_format),
    content = function(file) {
      gt::gtsave(getSummariseMedicationAdherenceTable(), file)
    }
  )
  # plot
  output$summarise_medication_adherence_plot <- plotly::renderPlotly({
    # First, create the base plot data and get ingredient levels
    plot_data <- getSummariseMedicationAdherenceData() %>% 
      tidy() %>%
      dplyr::mutate(
        mean = as.numeric(group_mean_cma),
        ci_lower_95 = as.numeric(ci_lower_95),
        ci_upper_95 = as.numeric(ci_upper_95),
        sd = as.numeric(group_sd_cma),
        ingredient = reorder(ingredient, mean),
        # Create custom hover text
        hover_text = paste0(
          "Medication group: ", ingredient, "<br>",
          "Source: ", cdm_name, "<br>",
          "CMA: ", variable_name, "<br>",
          "Mean: ", round(mean, 3), "<br>",
          "95% CI: [", round(ci_lower_95, 3), ", ", round(ci_upper_95, 3), "]"
        )
      )
    
    # Get ingredient levels for separator lines
    ingredient_levels <- levels(plot_data$ingredient)
    n_ingredients <- length(ingredient_levels)
    
    # Create separator positions (between each ingredient)
    separators <- data.frame(
      yintercept = seq(1.5, n_ingredients - 0.5, by = 1)
    )
    
    # Create the plot
    p <- plot_data %>%
      dplyr::mutate(
        # Create interaction for dodging by both cdm_name and variable_name
        dodge_group = interaction(cdm_name, variable_name)
      ) %>%
      ggplot(aes(x = mean, y = ingredient, 
                 color = variable_name, 
                 group = dodge_group,
                 text = hover_text)) +
      # Add horizontal separator lines
      geom_hline(
        data = separators,
        aes(yintercept = yintercept),
        color = "grey85",
        linewidth = 0.5,
        linetype = "solid"
      ) +
      geom_point(
        size = 1.5,
        position = position_dodge(width = 0.5)
      ) +
      geom_errorbarh(
        aes(xmin = ci_lower_95, xmax = ci_upper_95),
        height = 0.15,
        linewidth = 0.6,
        position = position_dodge(width = 0.5)
      ) +
      scale_color_brewer(palette = "Set2") +
      labs(
        x = "Average CMA",#"Average CMA",
        y = "",
        title = "",
        color = "CMA type"#"CDM Name"
      ) +
      theme_minimal(base_size = 12) +
      theme(
        panel.grid.major.y = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.y = element_text(size = 9),
        plot.title = element_text(hjust = 0.5, face = "bold"),
        axis.title.y = element_text(margin = margin(r = 10)),
        axis.title.x = element_text(margin = margin(t = 10)),
        legend.position = "right"
      )
    
    plotly::ggplotly(p, tooltip = "text")
    
    plotly::ggplotly(p, tooltip = "text")
    
    
  })
  
  # summarise_medication_adherence_cma_over_0.8 -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_medication_adherence_cma_over_0.8 <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_medication_adherence_cma_over_0.8_cdm_name,
      input$summarise_medication_adherence_cma_over_0.8_ingredient,
      input$summarise_medication_adherence_cma_over_0.8_age_group,
      input$summarise_medication_adherence_cma_over_0.8_sex,
      input$summarise_medication_adherence_cma_over_0.8_variable_name,
      input$summarise_medication_adherence_cma_over_0.8_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_medication_adherence_cma_over_0.8, {
    if (updateButtons$summarise_medication_adherence_cma_over_0.8 == TRUE) {
      output$update_message_summarise_medication_adherence_cma_over_0.8 <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_medication_adherence_cma_over_0.8 <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_medication_adherence_cma_over_0.8, {
    updateButtons$summarise_medication_adherence_cma_over_0.8 <- FALSE
  })
  
  ## get summarise_medication_adherence_cma_over_0.8 data
  getSummariseMedicationAdherenceCmaOver0_8Data <- shiny::eventReactive(input$update_summarise_medication_adherence_cma_over_0.8, {
    #print(input$summarise_medication_adherence_cma_over_0.8_age_group)
    data[["summarise_medication_adherence_cma_over_0.8"]] |>
      dplyr::arrange(strata_level) |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_medication_adherence_cma_over_0.8_cdm_name,
        .data$variable_name %in% input$summarise_medication_adherence_cma_over_0.8_variable_name,
        .data$estimate_name %in% input$summarise_medication_adherence_cma_over_0.8_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$ingredient %in% input$summarise_medication_adherence_cma_over_0.8_ingredient) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_medication_adherence_cma_over_0.8_age_group,
        .data$sex %in% input$summarise_medication_adherence_cma_over_0.8_sex
      ) 
  })
  getSummariseMedicationAdherenceCmaOver0_8Tidy <- shiny::reactive({
    tidyDT(getSummariseMedicationAdherenceCmaOver0_8Data(), input$summarise_medication_adherence_cma_over_0.8_tidy_columns, input$summarise_medication_adherence_cma_over_0.8_tidy_pivot_estimates)
  })
  output$summarise_medication_adherence_cma_over_0.8_tidy <- DT::renderDT({
    getSummariseMedicationAdherenceCmaOver0_8Tidy()
  })
  output$summarise_medication_adherence_cma_over_0.8_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseMedicationAdherenceCmaOver0_8Data() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseMedicationAdherenceCmaOver0_8Table <- shiny::reactive({
    getSummariseMedicationAdherenceCmaOver0_8Data() |>
      simpleTable(
        header = input$summarise_medication_adherence_cma_over_0.8_table_header,
        group = input$summarise_medication_adherence_cma_over_0.8_table_group_column,
        hide = input$summarise_medication_adherence_cma_over_0.8_table_hide
      )
  })
  output$summarise_medication_adherence_cma_over_0.8_table <- gt::render_gt({
    getSummariseMedicationAdherenceCmaOver0_8Table()
  })
  output$summarise_medication_adherence_cma_over_0.8_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_medication_adherence_cma_over_0.8_table_format),
    content = function(file) {
      gt::gtsave(getSummariseMedicationAdherenceCmaOver0_8Table(), file)
    }
  )
  
  output$summarise_medication_adherence_cma_over_0.8_plot <- plotly::renderPlotly({
    
    plot_data <- getSummariseMedicationAdherenceCmaOver0_8Data() %>%
      tidy() %>%
      dplyr::filter(age_group != "overall") %>%
      dplyr::mutate(
        percentage = as.numeric(pct_adherent),
        age_group = factor(age_group)
      ) 
    
    age_data <- plot_data %>%
      dplyr::filter(age_group != "overall")
    
    # Get x-axis range from age_data for segment spanning
    x_levels <- levels(age_data$age_group)
    x_min <- x_levels[1]
    x_max <- x_levels[length(x_levels)]
    
    # Build color mapping to match between lines and overall segments
    color_groups <- unique(interaction(age_data$cdm_name, age_data$variable_name, sep = " - "))
    n_colors <- length(color_groups)
    color_palette <- RColorBrewer::brewer.pal(max(3, n_colors), "Set2")[1:n_colors]
    color_map <- setNames(color_palette, levels(color_groups))
    
    # Count number of unique ingredients
    n_ingredients <- length(unique(plot_data$ingredient))
    height_per_ingredient <- 350
    
    # Create the plot
    p <- age_data %>%
      dplyr::mutate(color_key = interaction(cdm_name, variable_name, sep = " - ")) %>%
      ggplot(aes(x = age_group, y = percentage,
                 color = color_key,
                 linetype = sex,
                 group = interaction(cdm_name, variable_name, sex))) +
      # Age-specific lines
      geom_line(linewidth = 1) +
      # Points for hover
      geom_point(
        aes(text = paste0(
          "Ingredient: ", ingredient, "<br>",
          "CDM: ", cdm_name, "<br>",
          "Variable: ", variable_name, "<br>",
          "Sex: ", sex, "<br>",
          "Age Group: ", age_group, "<br>",
          "Percentage: ", round(percentage, 1), "%<br>",
          "Count: ", n_people_adherent, " / ", n_people_total
        ), size = n_people_total)
      ) +
      scale_size(range = c(1, 6)) + 
      facet_wrap(
        ~ ingredient,
        ncol = 1,
        scales = "free_x"
      ) +
      scale_color_manual(values = color_map) +
      scale_linetype_manual(values = c("overall"="solid", "Female"="dotted", "Male"="dashed")) +
      scale_x_discrete(drop = FALSE) +
      labs(
        x = "Age Group",
        y = "Percentage with Adherence > 0.8 (%)",
        color = "CDM - Variable",
        linetype = "Sex"
      ) +
      theme_minimal(base_size = 12) +
      theme(
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 9, vjust = 1),
        axis.text.y = element_text(size = 10),
        axis.title.x = element_text(size = 12, face = "bold", margin = margin(t = 10)),
        axis.title.y = element_text(size = 12, face = "bold", margin = margin(r = 10)),
        strip.text = element_text(face = "bold", size = 11),
        strip.background = element_rect(fill = "grey95", color = "grey80", linewidth = 0.5),
        plot.title = element_text(hjust = 0.5, face = "bold"),
        legend.position = "right",
        panel.spacing = unit(1.5, "lines"),
        axis.ticks.x = element_line(color = "grey50"),
        axis.ticks.length.x = unit(0.2, "cm")
      ) 
    # Convert to plotly
    plotly::ggplotly(p, tooltip = "text", height = n_ingredients * height_per_ingredient)
    
    
  })
  # summarise_mean_continuous_adherence_window -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_mean_continuous_adherence_window <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_mean_continuous_adherence_window_cdm_name,
      input$summarise_mean_continuous_adherence_window_ingredient,
      input$summarise_mean_continuous_adherence_window_age_group,
      input$summarise_mean_continuous_adherence_window_sex,
      input$summarise_mean_continuous_adherence_window_variable_name,
      input$summarise_mean_continuous_adherence_window_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_mean_continuous_adherence_window, {
    if (updateButtons$summarise_mean_continuous_adherence_window == TRUE) {
      output$update_message_summarise_mean_continuous_adherence_window <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_mean_continuous_adherence_window <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_mean_continuous_adherence_window, {
    updateButtons$summarise_mean_continuous_adherence_window <- FALSE
  })
  
  
  
  # get summarise_mean_continuous_adherence_window data
  getSummariseMeanContinuousAdherenceWindowData <- shiny::eventReactive(input$update_summarise_mean_continuous_adherence_window, {
    data[["summarise_mean_continuous_adherence_window"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_mean_continuous_adherence_window_cdm_name,
        .data$variable_name %in% input$summarise_mean_continuous_adherence_window_variable_name,
        .data$estimate_name %in% input$summarise_mean_continuous_adherence_window_estimate_name
      )|>
      dplyr::arrange(strata_level) |>
      omopgenerics::filterGroup(.data$ingredient %in% input$summarise_mean_continuous_adherence_window_ingredient) |>
      omopgenerics::filterStrata(
        #.data$age_group %in% input$summarise_mean_continuous_adherence_window_age_group,
        .data$sex %in% input$summarise_mean_continuous_adherence_window_sex
      )
  })
  getSummariseMeanContinuousAdherenceWindowTidy <- shiny::reactive({
    tidyDT(getSummariseMeanContinuousAdherenceWindowData(), input$summarise_mean_continuous_adherence_window_tidy_columns, input$summarise_mean_continuous_adherence_window_tidy_pivot_estimates)
  })
  
  output$summariseMeanContinuousAdherenceWindow_plot <- plotly::renderPlotly({
    
    km_plot_data <- getSummariseMeanContinuousAdherenceWindowData() %>%
      tidy() %>%
      mutate(
        time  = as.factor(as.numeric(time_years)),
        surv  = as.numeric(surv),
        lower = as.numeric(lower),
        upper = as.numeric(upper)
      ) 
    
    # Plot
    n_ingredients <- length(unique(km_plot_data$ingredient))
    height_per_ingredient <- 350
    
    p <- km_plot_data %>%
      dplyr::mutate(dodge_group = interaction(cdm_name, variable_name)) %>%
      dplyr::group_by(dodge_group, sex, ingredient) %>%
      dplyr::arrange(time, .by_group = TRUE) %>%
      dplyr::mutate(
        # For drawing: carry last known value forward so the line stays continuous
        # The original surv/lower/upper are preserved in tooltip columns
        surv_draw  = zoo::na.locf(surv,  na.rm = FALSE),
        lower_draw = zoo::na.locf(lower, na.rm = FALSE),
        upper_draw = zoo::na.locf(upper, na.rm = FALSE),
        # Tooltip: show suppressed label when NA
        surv_label  = dplyr::if_else(is.na(surv),  "suppressed (k<5)", paste0(round(surv  * 100, 3), "%")),
        lower_label = dplyr::if_else(is.na(lower), "suppressed (k<5)", paste0(round(lower * 100, 3), "%")),
        upper_label = dplyr::if_else(is.na(upper), "suppressed (k<5)", paste0(round(upper * 100, 3), "%"))
      ) %>%
      dplyr::ungroup() %>%
      ggplot(aes(
        x     = time,
        y     = surv_draw,           # draw on filled values
        color = sex,
        fill  = sex,
        group = dodge_group,
        text  = paste0(
          "CDM: ",      cdm_name,    "<br>",
          "Variable: ", variable_name, "<br>",
          "Sex: ",      sex,         "<br>",
          "Survival: ", surv_label,  "<br>",
          "Lower: ",    lower_label, "<br>",
          "Upper: ",    upper_label, "<br>",
          "Years: ",    time
        )
      )) +
      geom_step(linewidth = 0.8, na.rm = TRUE) +
      # geom_ribbon( # TODO imelikud jooned step_ribbon
      #   aes(ymin = lower_draw, ymax = upper_draw),
      #   alpha    = 0.15,
      #   linetype = 0,
      #   na.rm    = TRUE
      # ) +
      scale_y_continuous(limits = c(0, 1), labels = scales::percent) +
      facet_wrap(~ ingredient, ncol = 1, scales = "free_x") +
      scale_x_discrete(drop = FALSE) +
      theme_minimal(base_size = 12) +
      theme(
        panel.grid.minor    = element_blank(),
        axis.text.x         = element_text(angle = 0, hjust = 1, size = 9, vjust = 1),
        axis.text.y         = element_text(size = 10),
        axis.title.x        = element_text(size = 12, face = "bold", margin = margin(t = 10)),
        axis.title.y        = element_blank(),#element_text(size = 12, face = "bold", margin = margin(r = 10)),
        strip.text          = element_text(face = "bold", size = 11),
        strip.background    = element_rect(fill = "grey95", color = "grey80", linewidth = 0.5),
        plot.title          = element_text(hjust = 0.5, face = "bold"),
        legend.position     = "right",
        panel.spacing       = unit(1.5, "lines"),
        axis.ticks.x        = element_line(color = "grey50"),
        axis.ticks.length.x = unit(0.2, "cm")
      )
    
    plotly::ggplotly(p, tooltip = "text", height = n_ingredients * height_per_ingredient)
    
  })
  
  
  output$summarise_mean_continuous_adherence_window_tidy <- DT::renderDT({
    getSummariseMeanContinuousAdherenceWindowTidy()
  })
  output$summarise_mean_continuous_adherence_window_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseMeanContinuousAdherenceWindowData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseMeanContinuousAdherenceWindowTable <- shiny::reactive({
    getSummariseMeanContinuousAdherenceWindowData() |>
      simpleTable(
        header = input$summarise_mean_continuous_adherence_window_table_header,
        group = input$summarise_mean_continuous_adherence_window_table_group_column,
        hide = input$summarise_mean_continuous_adherence_window_table_hide
      )
  })
  output$summarise_mean_continuous_adherence_window_table <- gt::render_gt({
    getSummariseMeanContinuousAdherenceWindowTable()
  })
  output$summarise_mean_continuous_adherence_window_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_mean_continuous_adherence_window_table_format),
    content = function(file) {
      gt::gtsave(getSummariseMeanContinuousAdherenceWindowTable(), file)
    }
  )
  
  #############################################################################
  #############################################################################
  shiny::observe({
    updateButtons$summarise_always_adherent <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_always_adherent_cdm_name,
      input$summarise_always_adherent_sex,
      input$summarise_always_adherent_number_of_periods,
      input$summarise_always_adherent_variable_name,
      input$summarise_always_adherent_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_always_adherent, {
    if (updateButtons$summarise_always_adherent == TRUE) {
      output$update_message_summarise_always_adherent <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_always_adherent <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_always_adherent, {
    updateButtons$summarise_always_adherent <- FALSE
  })
  
  ## get summarise_always_adherent data
  getSummariseAlwaysAdherentData <- shiny::eventReactive(input$update_summarise_always_adherent, {
    #print(data[["summarise_always_adherent"]])
    data[["summarise_always_adherent"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_always_adherent_cdm_name,
        .data$variable_name %in% input$summarise_always_adherent_variable_name,
        .data$estimate_name %in% input$summarise_always_adherent_estimate_name
      ) |>
      omopgenerics::filterStrata(.data$sex %in% input$summarise_always_adherent_sex) #|>
    #omopgenerics::filterAdditional(.data$number_of_periods %in% input$summarise_always_adherent_number_of_periods)
  })
  getSummariseAlwaysAdherentTidy <- shiny::reactive({
    tidyDT(getSummariseAlwaysAdherentData(), input$summarise_always_adherent_tidy_columns, input$summarise_always_adherent_tidy_pivot_estimates)
  })
  output$summarise_always_adherent_tidy <- DT::renderDT({
    getSummariseAlwaysAdherentTidy()
  })
  output$summarise_always_adherent_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseAlwaysAdherentData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseAlwaysAdherentTable <- shiny::reactive({
    getSummariseAlwaysAdherentData() |>
      simpleTable(
        header = input$summarise_always_adherent_table_header,
        group = input$summarise_always_adherent_table_group_column,
        hide = input$summarise_always_adherent_table_hide
      )
  })
  output$summarise_always_adherent_table <- gt::render_gt({
    getSummariseAlwaysAdherentTable()
  })
  output$summarise_always_adherent_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_always_adherent_table_format),
    content = function(file) {
      gt::gtsave(getSummariseAlwaysAdherentTable(), file)
    }
  )
  #####################################################################
  #############################################################################
  shiny::observe({
    updateButtons$summarise_adherence_breaks <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_adherence_breaks_cdm_name,
      input$summarise_adherence_breaks_sex,
      input$summarise_adherence_breaks_threshold_years,
      input$summarise_adherence_breaks_variable_name,
      input$summarise_adherence_breaks_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_adherence_breaks, {
    if (updateButtons$summarise_adherence_breaks == TRUE) {
      output$update_message_summarise_adherence_breaks <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_adherence_breaks <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_adherence_breaks, {
    updateButtons$summarise_adherence_breaks <- FALSE
  })
  
  ## get summarise_adherence_breaks data
  getSummariseAdherenceBreaksData <- shiny::eventReactive(input$update_summarise_adherence_breaks, {
    data[["summarise_adherence_breaks"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_adherence_breaks_cdm_name,
        .data$variable_name %in% input$summarise_adherence_breaks_variable_name,
        .data$estimate_name %in% input$summarise_adherence_breaks_estimate_name,
        .data$additional_level %in% input$summarise_adherence_breaks_threshold_years
      ) |>
      omopgenerics::filterStrata(.data$sex %in% input$summarise_adherence_breaks_sex) #|>
    #omopgenerics::filterAdditional(.data$additional_level %in% input$summarise_adherence_breaks_threshold_years)
  })
  getSummariseAdherenceBreaksTidy <- shiny::reactive({
    tidyDT(getSummariseAdherenceBreaksData(), input$summarise_adherence_breaks_tidy_columns, input$summarise_adherence_breaks_tidy_pivot_estimates)
  })
  output$summarise_adherence_breaks_tidy <- DT::renderDT({
    getSummariseAdherenceBreaksTidy()
  })
  output$summarise_adherence_breaks_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseAdherenceBreaksData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseAdherenceBreaksTable <- shiny::reactive({
    getSummariseAdherenceBreaksData() |>
      simpleTable(
        header = input$summarise_adherence_breaks_table_header,
        group = input$summarise_adherence_breaks_table_group_column,
        hide = input$summarise_adherence_breaks_table_hide
      )
  })
  output$summarise_adherence_breaks_table <- gt::render_gt({
    getSummariseAdherenceBreaksTable()
  })
  output$summarise_adherence_breaks_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_adherence_breaks_table_format),
    content = function(file) {
      gt::gtsave(getSummariseAdherenceBreaksTable(), file)
    }
  )
 
  
  
  
}
