# Generated by OmopViewer 0.6.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = "MAS results analysis",
  theme = bslib::bs_theme(brand = TRUE),
  shiny::tags$style(HTML(
    ".sticky-top-btn {
      position: sticky;
      top: 0;
      z-index: 20;
      background: var(--bs-body-bg);
    }"
  )),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    bslib::card(
      bslib::card_header("Explore results"),
      shiny::tags$div(
        class = "mb-2",
        shinyTree::shinyTree("summary_cdm_name", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_packages", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_min_cell_count", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_panels", theme = "proton", themeIcons = FALSE)
      ),
      full_screen = TRUE
    )
  ),
  bslib::nav_panel(
    title = "Summarise medication adherence",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_medication_adherence",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_medication_adherence")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_cdm_name",
          label = "CDM name",
          choices = choices$summarise_medication_adherence_cdm_name,
          selected = selected$summarise_medication_adherence_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_ingredient",
          label = "Ingredient",
          choices = choices$summarise_medication_adherence_ingredient,
          selected = choices$summarise_medication_adherence_ingredient[1:5],#selected$summarise_medication_adherence_ingredient,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_age_group",
          label = "Age group",
          choices = choices$summarise_medication_adherence_age_group,
          selected = c("overall"),#selected$summarise_medication_adherence_age_group,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_sex",
          label = "Sex",
          choices = choices$summarise_medication_adherence_sex,
          selected = c("overall"), #choices$summarise_medication_adherence_sex
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_variable_name",
          label = "Variable name",
          choices = choices$summarise_medication_adherence_variable_name,
          selected = selected$summarise_medication_adherence_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_medication_adherence_estimate_name,
          selected = selected$summarise_medication_adherence_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        position = "left"
      ),
      div("Average adherence values"),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Plot",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_medication_adherence_plot_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "png",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::downloadButton(outputId = "summarise_medication_adherence_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            
            plotly::plotlyOutput("summarise_medication_adherence_plot") 
            
          )
        ),
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_medication_adherence_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_medication_adherence_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "ingredient", "age_group", "sex", "variable_name", "variable_level"),
                  selected = c("cdm_name", "ingredient", "age_group", "sex", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::checkboxInput(
                  inputId = "summarise_medication_adherence_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("summarise_medication_adherence_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_medication_adherence_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::downloadButton(outputId = "summarise_medication_adherence_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "variable_name", "estimate_name"),
                    input_id = "summarise_medication_adherence_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = c("age_group", "sex"),
                    input_id = "summarise_medication_adherence_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = c("ingredient"),
                    input_id = "summarise_medication_adherence_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = c("variable_level"),
                    input_id = "summarise_medication_adherence_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_medication_adherence_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Summarise medication adherence cma over 0.8",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_medication_adherence_cma_over_0.8",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_medication_adherence_cma_over_0.8")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_cma_over_0.8_cdm_name",
          label = "CDM name",
          choices = choices$summarise_medication_adherence_cma_over_0.8_cdm_name,
          selected = selected$summarise_medication_adherence_cma_over_0.8_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_cma_over_0.8_ingredient",
          label = "Ingredient",
          choices = choices$summarise_medication_adherence_cma_over_0.8_ingredient,
          selected = choices$summarise_medication_adherence_cma_over_0.8_ingredient[1:5],#selected$summarise_medication_adherence_cma_over_0.8_ingredient,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_cma_over_0.8_age_group",
          label = "Age group",
          choices = choices$summarise_medication_adherence_cma_over_0.8_age_group,
          selected = selected$summarise_medication_adherence_cma_over_0.8_age_group, ###
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_cma_over_0.8_sex",
          label = "Sex",
          choices = choices$summarise_medication_adherence_cma_over_0.8_sex,
          selected = c("overall"),#selected$summarise_medication_adherence_cma_over_0.8_sex,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_cma_over_0.8_variable_name",
          label = "Variable name",
          choices = choices$summarise_medication_adherence_cma_over_0.8_variable_name,
          selected = selected$summarise_medication_adherence_cma_over_0.8_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_medication_adherence_cma_over_0.8_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_medication_adherence_cma_over_0.8_estimate_name,
          selected = selected$summarise_medication_adherence_cma_over_0.8_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        position = "left"
      ),
      div("Proportion of patients whose personal average CMA is at least 0.8."),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Plot",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_medication_adherence_cma_over_0.8_plot_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "png",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::downloadButton(outputId = "summarise_medication_adherence_cma_over_0.8_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            
            plotly::plotlyOutput("summarise_medication_adherence_cma_over_0.8_plot") 
            
          )
        ),
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_medication_adherence_cma_over_0.8_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_medication_adherence_cma_over_0.8_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "ingredient", "age_group", "sex", "variable_name", "variable_level"),
                  selected = c("cdm_name", "ingredient", "age_group", "sex", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::checkboxInput(
                  inputId = "summarise_medication_adherence_cma_over_0.8_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("summarise_medication_adherence_cma_over_0.8_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_medication_adherence_cma_over_0.8_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::downloadButton(outputId = "summarise_medication_adherence_cma_over_0.8_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "variable_name", "estimate_name"),
                    input_id = "summarise_medication_adherence_cma_over_0.8_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = c("age_group", "sex"),
                    input_id = "summarise_medication_adherence_cma_over_0.8_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = c("ingredient"),
                    input_id = "summarise_medication_adherence_cma_over_0.8_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = c("variable_level"),
                    input_id = "summarise_medication_adherence_cma_over_0.8_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_medication_adherence_cma_over_0.8_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Continuous adherence",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_mean_continuous_adherence_window",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_mean_continuous_adherence_window")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_mean_continuous_adherence_window_cdm_name",
          label = "CDM name",
          choices = choices$summarise_mean_continuous_adherence_window_cdm_name,
          selected = selected$summarise_mean_continuous_adherence_window_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_mean_continuous_adherence_window_ingredient",
          label = "Ingredient",
          choices = choices$summarise_mean_continuous_adherence_window_ingredient,
          selected = choices$summarise_mean_continuous_adherence_window_ingredient[1:5],#selected$summarise_mean_continuous_adherence_window_ingredient,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        # shinyWidgets::pickerInput(
        #   inputId = "summarise_mean_continuous_adherence_window_age_group",
        #   label = "Age group",
        #   choices = choices$summarise_mean_continuous_adherence_window_age_group,
        #   selected = selected$summarise_mean_continuous_adherence_window_age_group,
        #   multiple = TRUE,
        #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        # ),
        shinyWidgets::pickerInput(
          inputId = "summarise_mean_continuous_adherence_window_sex",
          label = "Sex",
          choices = choices$summarise_mean_continuous_adherence_window_sex,
          selected = selected$summarise_mean_continuous_adherence_window_sex,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_mean_continuous_adherence_window_variable_name",
          label = "Variable name",
          choices = choices$summarise_mean_continuous_adherence_window_variable_name,
          selected = c("CMA5"),#selected$summarise_mean_continuous_adherence_window_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_mean_continuous_adherence_window_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_mean_continuous_adherence_window_estimate_name,
          selected = selected$summarise_mean_continuous_adherence_window_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        position = "left"
      ),
      div("Continuous adherence = an uninterrupted run of windows. The event of interest is discontinuation. Only 'new chronic patients' are included: those whose very first prescription started more than 364 days after observation began,
ensuring they are incident users rather than prevalent users."),
      bslib::navset_card_tab(
        
        bslib::nav_panel(
          title = "Plot",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_medication_adherence_cma_over_0.8_plot_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "png",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::downloadButton(outputId = "summarise_medication_adherence_cma_over_0.8_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            
            plotly::plotlyOutput("summariseMeanContinuousAdherenceWindow_plot") 
            
          )
        ),
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_mean_continuous_adherence_window_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_mean_continuous_adherence_window_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "ingredient", "age_group", "sex", "variable_name", "variable_level"),
                  selected = c("cdm_name", "ingredient", "age_group", "sex", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::checkboxInput(
                  inputId = "summarise_mean_continuous_adherence_window_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("summarise_mean_continuous_adherence_window_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_mean_continuous_adherence_window_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::downloadButton(outputId = "summarise_mean_continuous_adherence_window_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "variable_name", "estimate_name"),
                    input_id = "summarise_mean_continuous_adherence_window_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = c("sex","time_years"),
                    input_id = "summarise_mean_continuous_adherence_window_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = c("ingredient"),
                    input_id = "summarise_mean_continuous_adherence_window_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = c("variable_level"),
                    input_id = "summarise_mean_continuous_adherence_window_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_mean_continuous_adherence_window_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
    ##### 
  ), 
  bslib::nav_panel(
    title = "Break analysis",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::card(
          class = "sticky-top-btn",
          bslib::card_body(
            shiny::actionButton(
              inputId = "update_summarise_adherence_breaks",
              label = "Update content",
              width = "100%"
            ),
            uiOutput(outputId = "update_message_summarise_adherence_breaks")
          )
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_adherence_breaks_cdm_name",
          label = "CDM name",
          choices = choices$summarise_adherence_breaks_cdm_name,
          selected = selected$summarise_adherence_breaks_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_adherence_breaks_sex",
          label = "Sex",
          choices = choices$summarise_adherence_breaks_sex,
          selected = selected$summarise_adherence_breaks_sex,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_adherence_breaks_threshold_years",
          label = "Break length",
          choices = choices$summarise_adherence_breaks_threshold_years,
          selected = selected$summarise_adherence_breaks_threshold_years,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_adherence_breaks_variable_name",
          label = "Variable name",
          choices = choices$summarise_adherence_breaks_variable_name,
          selected = selected$summarise_adherence_breaks_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_adherence_breaks_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_adherence_breaks_estimate_name,
          selected = selected$summarise_adherence_breaks_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
        ),
        position = "left"
      ),
      div("For each ingredient and threshold (2, 3, and 4 years), we report the number and proportion of patients who restarted medication within the threshold period after their first break. The denominator consists of patients who had at least one break in medication after initiating treatment and remained under observation for at least the threshold number of years after the break began. The numerator consists of those patients who restarted the same medication within the threshold period. Patients who never restarted or restarted after the threshold period are included in the denominator but not the numerator. Only each patient's first break is considered."),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_adherence_breaks_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_adherence_breaks_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "ingredient", "sex", "number_of_periods", "variable_name", "variable_level"),
                  selected = c("cdm_name", "ingredient", "sex", "number_of_periods", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::checkboxInput(
                  inputId = "summarise_adherence_breaks_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("summarise_adherence_breaks_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_adherence_breaks_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 4")
                ),
                shiny::downloadButton(outputId = "summarise_adherence_breaks_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "number_of_periods", "variable_name", "estimate_name"),
                    input_id = "summarise_adherence_breaks_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = c("sex"),
                    input_id = "summarise_adherence_breaks_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = c("ingredient"),
                    input_id = "summarise_adherence_breaks_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = c("variable_level"),
                    input_id = "summarise_adherence_breaks_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_adherence_breaks_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  ###############
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.6.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
